services:
  tagoio-mqtt-relay:
    image: tagoio/relay:latest
    restart: always
    pull_policy: if_not_present
    depends_on:
      - mosquitto-broker
    ports:
      # Port for the TCP server
      - "3001:3001"
    command: ["start", "--unsafe-mode"]

    # Set the path to the .tagoio-mqtt-relay.toml file to configure the relay
    # volumes:
    # - .tagoio-mqtt-relay.toml:/root/.config/.tagoio-mqtt-relay.toml

    # Example using the environment variables for easy setup. You can use the .tagoio-mqtt-relay.toml above instead if you prefer.
    environment:
      # TagoIO Related Settings
      - TAGOIO__RELAY__NETWORK_TOKEN=Your-Network-Token
      - TAGOIO__RELAY__AUTHORIZATION_TOKEN=Your-Authorization-Token

      # Mosquitto Broker Settings for the Relay to connect to
      - TAGOIO__RELAY__MQTT__ADDRESS=mosquitto-broker
      - TAGOIO__RELAY__MQTT__PORT=8883
      - TAGOIO__RELAY__MQTT__TLS_ENABLED=true
      - TAGOIO__RELAY__MQTT__CLIENT_ID=tagoio-relay
      - TAGOIO__RELAY__MQTT__USERNAME=token
      - TAGOIO__RELAY__MQTT__PASSWORD=A-Device-Token # Needs to use a Device-Token for the relay to be able to connect
      - TAGOIO__RELAY__MQTT__SUBSCRIBE=["/device/#"]

      # Certificate Paths
      # - TAGOIO__RELAY__MQTT__BROKER_TLS_CA=""
      # - TAGOIO__RELAY__MQTT__BROKER_TLS_CERT=""
      # - TAGOIO__RELAY__MQTT__BROKER_TLS_KEY=""

  mosquitto-broker:
    image: iegomez/mosquitto-go-auth:latest
    restart: unless-stopped
    pull_policy: if_not_present
    environment:
      - http_host=tagoio-mqtt-relay
      - http_port=3001
    ports:
      - "1883:1883"
      - "8883:8883" # Port for TLS
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
